# Generated by Django 4.2.2 on 2023-07-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_fluxo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.AlterField(
            model_name='activities',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_fluxo.bank'),
        ),
    ]
